### ISSUE TITLE
FZF Search Manga Chooser (Nested Dual Search)

### ISSUE THREAD

**Issue by 4cecoder** [manga-g/manga-g#2]
# comparable to features in mov-cli 

## can cycle through options with arrow keys
- prefer adding vim like key binding to  j and k for up and down respectively  
  
## nested dual search
 - how about a second step fzf that actively filters while typing before you choose? 
    - one single search
        - one active (reactive) search based on input closest matches

**Comment by iamchokerman** [comment]
do u know about Ctrl+j and Ctrl+k in fzf? they're there by default

**Comment by 4cecoder** [comment]
> do u know about Ctrl+j and Ctrl+k in fzf? they're there by default

working in golang though so...so building this behavior in from little knowledge about how fzf works behind the hood

**Comment by iamchokerman** [comment]
oh well, that's a different thing then

**Comment by 4cecoder** [comment]
yep
