### ISSUE TITLE
[ENHANCEMENT] Documentation site is not working

### ISSUE THREAD

**Issue by whinee** [manga-g/manga-g#24]
# Issue

Type: Enhancement suggestion: Documentation, Repository

## **Summary**

The docs site isn't working.

## **Proposed Changes**

Move the documentation to `manga-g/docs` repository and change its structure so that it could be hosted with Github instead.

---

<h6><i><b><a target="_blank" href="https://github.com/whinee">whi_ne</a> has been paid to help with this project.</b></i></h6>

<h6><i>Want help in your projects too? Inquire through Discord(<a target="_blank" href="https://discord.com/users/867696753434951732">whi_ne | whinyaan.xyz#5135</a>) or through e-mail(<a target="_blank" href="mailto:whinyaan@protonmail.com">whinyaan@protonmail.com</a>). Price starts at 50 USD. For commissioning projects, price starts at 30 USD.</i></h6>

---

**Comment by whinee** [comment]
Oof, @4cecoder actually hosted it on netlify. In any case, problem solved.

On to #25, we go!

**Comment by 4cecoder** [comment]
now both are working

**Comment by 4cecoder** [comment]
redundancy
