### ISSUE TITLE
[Enhancement] Set a color scheme within site branch code

### ISSUE THREAD

**Issue by 4cecoder** [manga-g/manga-g#27]
set documentation  site to use a set of hex codes that are coordinated

**Comment by 4cecoder** [comment]
72B1BC
7D5E93
02ABAA
AC6845
D86947

**Comment by whinee** [comment]
My suggestion is to let users make their own color scheme too.

Does manga-g use a config file? If not, this is a great opportunity to do so!

**Comment by 4cecoder** [comment]
![manga-g](https://user-images.githubusercontent.com/88108711/169731527-9a8887d2-b72e-46e4-a96d-88363ca66094.png)

**Comment by whinee** [comment]
Oh, right. I misunderstood. This is for the site.

**Comment by whinee** [comment]
Err... mind reconsidering the color scheme. Your proposed color scheme seems a little bit out of place and does not fit a website. This is your recommended color scheme:

<img src="https://embed.whinyaan.xyz/png/PHN2ZyByb2xlPSdpbWcnIHZpZXdCb3g9JzAgMCAxNTAwIDMwMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJz48cmVjdCBmaWxsPScjNzJCMUJDJyB4PScwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyM3RDVFOTMnIHg9JzMwMCcgeT0nMCcgd2lkdGg9JzMwMCcgaGVpZ2h0PSczMDAnLz48cmVjdCBmaWxsPScjMDJBQkFBJyB4PSc2MDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PHJlY3QgZmlsbD0nI0FDNjg0NScgeD0nOTAwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyNEODY5NDcnIHg9JzEyMDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PC9zdmc+" />

---

## **Recommendations**

For a sweet color scheme, I would recommend the following:

`ff99c8`, `fcf6bd`, `d0f4de`, `a9def9`, `e4c1f9`

<img src="https://embed.whinyaan.xyz/png/PHN2ZyByb2xlPSdpbWcnIHZpZXdCb3g9JzAgMCAxNTAwIDMwMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJz48cmVjdCBmaWxsPScjZmY5OWM4JyB4PScwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyNmY2Y2YmQnIHg9JzMwMCcgeT0nMCcgd2lkdGg9JzMwMCcgaGVpZ2h0PSczMDAnLz48cmVjdCBmaWxsPScjZDBmNGRlJyB4PSc2MDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PHJlY3QgZmlsbD0nI2E5ZGVmOScgeD0nOTAwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyNlNGMxZjknIHg9JzEyMDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PC9zdmc+" />

---

A monochromatic, mellow and pastel-y, yet sweet:

`ffd6ff`, `e7c6ff`, `c8b6ff`, `b8c0ff`, `bbd0ff`

<img src="https://embed.whinyaan.xyz/png/PHN2ZyByb2xlPSdpbWcnIHZpZXdCb3g9JzAgMCAxNTAwIDMwMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJz48cmVjdCBmaWxsPScjZmZkNmZmJyB4PScwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyNlN2M2ZmYnIHg9JzMwMCcgeT0nMCcgd2lkdGg9JzMwMCcgaGVpZ2h0PSczMDAnLz48cmVjdCBmaWxsPScjYzhiNmZmJyB4PSc2MDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PHJlY3QgZmlsbD0nI2I4YzBmZicgeD0nOTAwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyNiYmQwZmYnIHg9JzEyMDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PC9zdmc+" />

This might need a little bit of tweaking, but other than that, it's good!

---

Might be a little too sweet, but a-okay for a sweet tooth like me:

`cdb4db`, `ffc8dd`, `ffafcc`, `bde0fe`, `a2d2ff`

<img src="https://embed.whinyaan.xyz/png/PHN2ZyByb2xlPSdpbWcnIHZpZXdCb3g9JzAgMCAxNTAwIDMwMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJz48cmVjdCBmaWxsPScjY2RiNGRiJyB4PScwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyNmZmM4ZGQnIHg9JzMwMCcgeT0nMCcgd2lkdGg9JzMwMCcgaGVpZ2h0PSczMDAnLz48cmVjdCBmaWxsPScjZmZhZmNjJyB4PSc2MDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PHJlY3QgZmlsbD0nI2JkZTBmZScgeD0nOTAwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyNhMmQyZmYnIHg9JzEyMDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PC9zdmc+" />

---

For a lively color scheme, I would like to recommend this one:

`ff595e`, `ffca3a`, `8ac926`, `1982c4`, `6a4c93`

<img src="https://embed.whinyaan.xyz/png/PHN2ZyByb2xlPSdpbWcnIHZpZXdCb3g9JzAgMCAxNTAwIDMwMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJz48cmVjdCBmaWxsPScjZmY1OTVlJyB4PScwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyNmZmNhM2EnIHg9JzMwMCcgeT0nMCcgd2lkdGg9JzMwMCcgaGVpZ2h0PSczMDAnLz48cmVjdCBmaWxsPScjOGFjOTI2JyB4PSc2MDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PHJlY3QgZmlsbD0nIzE5ODJjNCcgeD0nOTAwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyM2YTRjOTMnIHg9JzEyMDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PC9zdmc+" />

---

This one might be a little bit too lively, so tweaking it is a must:

`ffbe0b`, `fb5607`, `ff006e`, `8338ec`, `3a86ff`

<img src="https://embed.whinyaan.xyz/png/PHN2ZyByb2xlPSdpbWcnIHZpZXdCb3g9JzAgMCAxNTAwIDMwMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJz48cmVjdCBmaWxsPScjZmZiZTBiJyB4PScwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyNmYjU2MDcnIHg9JzMwMCcgeT0nMCcgd2lkdGg9JzMwMCcgaGVpZ2h0PSczMDAnLz48cmVjdCBmaWxsPScjZmYwMDZlJyB4PSc2MDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PHJlY3QgZmlsbD0nIzgzMzhlYycgeD0nOTAwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyMzYTg2ZmYnIHg9JzEyMDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PC9zdmc+" />

---

A fairly safe choice:

`9381ff`, `b8b8ff`, `ffd8be`

<img src="https://embed.whinyaan.xyz/png/PHN2ZyByb2xlPSdpbWcnIHZpZXdCb3g9JzAgMCA5MDAgMzAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPjxyZWN0IGZpbGw9JyM5MzgxZmYnIHg9JzAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PHJlY3QgZmlsbD0nI2I4YjhmZicgeD0nMzAwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyNmZmQ4YmUnIHg9JzYwMCcgeT0nMCcgd2lkdGg9JzMwMCcgaGVpZ2h0PSczMDAnLz48L3N2Zz4=" />

---

Another hot color scheme:

`ffcdb2`, `ffb4a2`, `e5989b`, `b5838d`, `6d6875`

<img src="https://embed.whinyaan.xyz/png/PHN2ZyByb2xlPSdpbWcnIHZpZXdCb3g9JzAgMCAxNTAwIDMwMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJz48cmVjdCBmaWxsPScjZmZjZGIyJyB4PScwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyNmZmI0YTInIHg9JzMwMCcgeT0nMCcgd2lkdGg9JzMwMCcgaGVpZ2h0PSczMDAnLz48cmVjdCBmaWxsPScjZTU5ODliJyB4PSc2MDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PHJlY3QgZmlsbD0nI2I1ODM4ZCcgeD0nOTAwJyB5PScwJyB3aWR0aD0nMzAwJyBoZWlnaHQ9JzMwMCcvPjxyZWN0IGZpbGw9JyM2ZDY4NzUnIHg9JzEyMDAnIHk9JzAnIHdpZHRoPSczMDAnIGhlaWdodD0nMzAwJy8+PC9zdmc+" />

This might also require a wee bit of effort to fit in the site.

---

<h6><i><b><a target="_blank" href="https://github.com/whinee">whi_ne</a> has been paid to help with this project.</b></i></h6>

<h6><i>Want help in your projects too? Inquire through Discord(<a target="_blank" href="https://discord.com/users/867696753434951732">whi_ne (w17e)| whinyaan.xyz#5135</a>) or through e-mail(<a target="_blank" href="mailto:whinyaan@protonmail.com">whinyaan@protonmail.com</a>). Price starts at 50 USD. For commissioning projects, price starts at 30 USD.</i></h6>

---

**Comment by whinee** [comment]
I have [committed](https://github.com/manga-g/manga-g/commit/3446054b83e7416cde33b531657bf371df94e1ef) to the [site branch](https://github.com/manga-g/manga-g/tree/site) an implementation of this recommendation. This has been pushed to have a look on how the finished product will look like. And when we're both satisfied with the results, I'll go ahead and iron out the inconsistencies this change has brought into the site.
