### ISSUE TITLE
Doesn't work on windows.

### ISSUE THREAD

**Issue by H4rldev** [manga-g/manga-g#49]
The program doesn't let you quit or do anything.

```
Online Manga is ready!
Enter your choice: (1-3)
1.) Search Manga
2.) Search Comics
3.) Exit
4
Invalid Option
Enter your choice: (1-3)
1.) Search Manga
2.) Search Comics
3.) Exit
3
Invalid Option
Enter your choice: (1-3)
1.) Search Manga
2.) Search Comics
3.) Exit
3
Invalid Option
Enter your choice: (1-3)
1.) Search Manga
2.) Search Comics
3.) Exit
3
Invalid Option
Enter your choice: (1-3)
1.) Search Manga
2.) Search Comics
3.) Exit
3
Invalid Option
Enter your choice: (1-3)
1.) Search Manga
2.) Search Comics
3.) Exit
1
Invalid Option
Enter your choice: (1-3)
1.) Search Manga
2.) Search Comics
3.) Exit
2
Invalid Option
Enter your choice: (1-3)
1.) Search Manga
2.) Search Comics
3.) Exit
```

Tried both repos.

**Comment by 4cecoder** [comment]
Thanks we are looking into this fix asap and should be done by end of day

**Comment by 4cecoder** [comment]
> The program doesn't let you quit or do anything.
> 
> ```
> Online Manga is ready!
> Enter your choice: (1-3)
> 1.) Search Manga
> 2.) Search Comics
> 3.) Exit
> 4
> Invalid Option
> Enter your choice: (1-3)
> 1.) Search Manga
> 2.) Search Comics
> 3.) Exit
> 3
> Invalid Option
> Enter your choice: (1-3)
> 1.) Search Manga
> 2.) Search Comics
> 3.) Exit
> 3
> Invalid Option
> Enter your choice: (1-3)
> 1.) Search Manga
> 2.) Search Comics
> 3.) Exit
> 3
> Invalid Option
> Enter your choice: (1-3)
> 1.) Search Manga
> 2.) Search Comics
> 3.) Exit
> 3
> Invalid Option
> Enter your choice: (1-3)
> 1.) Search Manga
> 2.) Search Comics
> 3.) Exit
> 1
> Invalid Option
> Enter your choice: (1-3)
> 1.) Search Manga
> 2.) Search Comics
> 3.) Exit
> 2
> Invalid Option
> Enter your choice: (1-3)
> 1.) Search Manga
> 2.) Search Comics
> 3.) Exit
> ```
> 
> Tried both repos.

What is your go version on windows?

**Comment by 4cecoder** [comment]
With new branch looks like issue is fixed
